charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/storageclass.yaml
charts/juicefs-csi-driver/values.yaml

add pathPattern in sc & fix some docs

add pathPattern in sc

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/values.yaml
charts/juicefs-s3-gateway/Chart.yaml
charts/juicefs-s3-gateway/README.md
charts/juicefs-s3-gateway/values.yaml

release 0.15.0

---

charts/juicefs-csi-driver/templates/storageclass.yaml
charts/juicefs-csi-driver/values.yaml

Signed-off-by: Felix Breuer <fbreuer@pm.me>

Add Annotations to StorageClass via values.yaml

---

charts/juicefs-csi-driver/templates/serviceaccount.yaml
charts/juicefs-csi-driver/values.yaml

2. tpl for controller serviceaccount annotations
Signed-off-by: Boris Komraz <bkomraz1@gmail.com>

1. annotations with tpl for node service account

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/NOTES.txt
charts/juicefs-csi-driver/values.yaml

When all parameters are none, it's pointless to create sc. Make it disable by default.

make sc disable by default

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/values.yaml

bump csi image to 0.18.1 and change helm chart version

release csi 0.18.1

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/serviceaccount.yaml

releated to https://github.com/juicedata/juicefs-csi-driver/pull/618

del useless rbac

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/mutatingwebhook.yaml

fix https://github.com/juicedata/charts/issues/53

fix Certificate missing IssuerRef

---

README.md
charts/juicefs-csi-driver/values.yaml

* simplify format, drop all markdown notations, similar to https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
* add more doc refs, and drop obsolete doc links

simplify comments format

---

charts/juicefs-csi-driver/templates/serviceaccount.yaml

related: https://github.com/juicedata/juicefs-csi-driver/pull/845

watch and list secret permissions to csi driver

---

charts/juicefs-csi-driver/templates/controller.yaml
charts/juicefs-csi-driver/values.yaml

depends on https://github.com/juicedata/juicefs-csi-driver/pull/850

introduce feature flag --cache-client-conf

---

charts/juicefs-csi-driver/templates/daemonset.yaml
charts/juicefs-csi-driver/templates/service.yaml

merge after https://github.com/juicedata/juicefs-csi-driver/pull/852

add prometheus scrape annotation

---

charts/juicefs-csi-driver/templates/service.yaml
charts/juicefs-csi-driver/values.yaml

related: https://github.com/juicedata/juicefs-csi-driver/pull/852

use a separate port for metrics

---

charts/juicefs-csi-driver/templates/controller.yaml
charts/juicefs-csi-driver/templates/daemonset.yaml
charts/juicefs-csi-driver/templates/secret.yaml
charts/juicefs-csi-driver/templates/service.yaml
charts/juicefs-csi-driver/templates/webhook.yaml
charts/juicefs-csi-driver/values.yaml

in serverless mode
1. Use EmptyDir instead of hostPath
2. Create serverless webhook
3. Disable csi daemonset
4. Do not use privileged security

feat: add serverless mode

---

charts/juicefs-csi-driver/templates/serviceaccount.yaml

ref: https://github.com/juicedata/juicefs-csi-driver/pull/870

rbac: add persistentvolumeclaims resource 

---

charts/juicefs-csi-driver/templates/configmap.yaml
charts/juicefs-csi-driver/templates/controller.yaml
charts/juicefs-csi-driver/templates/daemonset.yaml
charts/juicefs-csi-driver/templates/serviceaccount.yaml
charts/juicefs-csi-driver/values.yaml

Introduce a global configuration file for csi to bring better configuration changes.
ref： https://github.com/juicedata/juicefs-csi-driver/issues/903 https://github.com/juicedata/juicefs-csi-driver/pull/938 https://github.com/juicedata/voc/issues/255

feat: introduce global config

---

charts/juicefs-csi-driver/templates/deployment.yaml
charts/juicefs-csi-driver/templates/secret.yaml
charts/juicefs-csi-driver/values.yaml

ref: https://github.com/juicedata/juicefs-csi-driver/pull/955

feat: add basic authentication for dashboard

---

charts/juicefs-s3-gateway/templates/deployment.yaml
charts/juicefs-s3-gateway/templates/secret.yaml
charts/juicefs-s3-gateway/values.yaml

based on https://github.com/juicedata/charts/pull/107

support encryption

---

charts/juicefs-csi-driver/templates/serviceaccount.yaml

fix: add `pods/exec` permission in serverless mode

---

.github/workflows/go.yaml
charts/juicefs-cache-group-operator/.helmignore
charts/juicefs-cache-group-operator/Chart.yaml
charts/juicefs-cache-group-operator/README.md
charts/juicefs-cache-group-operator/crds/crd.yaml
charts/juicefs-cache-group-operator/templates/NOTES.txt
charts/juicefs-cache-group-operator/templates/_helpers.tpl
charts/juicefs-cache-group-operator/templates/deployment.yaml
charts/juicefs-cache-group-operator/templates/rbac.yaml
charts/juicefs-cache-group-operator/templates/serviceaccount.yaml
charts/juicefs-cache-group-operator/values.yaml

Add juicefs cache group operator

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/values.yaml

release v0.25.2

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/configmap.yaml
charts/juicefs-csi-driver/values.yaml

fix juicefs-csi-driver cm update

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/values.yaml

Follow the old version rules to avoid deleting the configmap during an upgrade.

Update `manageByHelm` default value to true

---

.github/workflows/helm-chart-release.yaml

skip package upload if release/tag already exists

fix chart release

---

charts/juicefs-cache-group-operator/Chart.yaml
charts/juicefs-cache-group-operator/README.md
charts/juicefs-cache-group-operator/crds/crd.yaml
charts/juicefs-cache-group-operator/templates/rbac.yaml
charts/juicefs-cache-group-operator/values.yaml

release operator 3.0

---

charts/juicefs-cache-group-operator/templates/dashboard.yaml
charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/templates/deployment.yaml

fix dashboard version check

---

charts/juicefs-csi-driver/Chart.yaml
charts/juicefs-csi-driver/README.md
charts/juicefs-csi-driver/values.yaml

bump csi-driver to 0.27.0

---

charts/juicefs-operator/Chart.yaml
charts/juicefs-operator/README.md
charts/juicefs-operator/templates/deployment.yaml
charts/juicefs-operator/values.yaml

bump operator to v0.6.5
